@warning_ignore("unused_signal")
class_name GameEventsAutoload
extends Node

## Global decoupled event bus for Eclipse Front

@warning_ignore("unused_signal")
signal target_selected(entity: Node)
@warning_ignore("unused_signal")
signal target_cleared()
@warning_ignore("unused_signal")
signal target_died(target: Node, killer: Node)
@warning_ignore("unused_signal")
signal attack_started(attacker: Node, target: Node)
@warning_ignore("unused_signal")
signal attack_hit(attacker: Node, target: Node, damage_result: RefCounted)
@warning_ignore("unused_signal")
signal attack_missed(attacker: Node, target: Node)
@warning_ignore("unused_signal")
signal attack_landed(attacker: Node, target: Node, damage_result: RefCounted)
@warning_ignore("unused_signal")
signal damage_dealt(damage_result: RefCounted, attacker: Node, target: Node)
@warning_ignore("unused_signal")
signal damage_received(damage_result: RefCounted, target: Node, attacker: Node)
@warning_ignore("unused_signal")
signal combat_healed(source: Node, target: Node, amount: float, source_name: String)
@warning_ignore("unused_signal")
signal mana_burned(source: Node, target: Node, amount: float, damage: float, source_name: String)
@warning_ignore("unused_signal")
signal shield_granted(source: Node, target: Node, amount: float, source_name: String)
@warning_ignore("unused_signal")
signal execution_triggered(source: Node, target: Node, threshold: float, bonus_damage: float, source_name: String)
@warning_ignore("unused_signal")
signal entity_killed(victim: Node, killer: Node)
@warning_ignore("unused_signal")
signal entity_died(entity: Node, killer: Node)
@warning_ignore("unused_signal")
signal hero_died(hero: Node, killer: Node, respawn_time: float)
@warning_ignore("unused_signal")
signal hero_respawned(hero: Node)
@warning_ignore("unused_signal")
signal creep_died(creep: Node, killer: Node)
@warning_ignore("unused_signal")
signal creep_attacked(creep: Node, attacker: Node)
@warning_ignore("unused_signal")
signal creep_damaged(creep: Node, attacker: Node, damage: float)
@warning_ignore("unused_signal")
signal neutral_died(neutral: Node, killer: Node)
@warning_ignore("unused_signal")
signal camp_spawned(camp: Node)
@warning_ignore("unused_signal")
signal camp_combat_started(camp: Node, attacker: Node)
@warning_ignore("unused_signal")
signal camp_cleared(camp: Node)
@warning_ignore("unused_signal")
signal camp_respawn_started(camp: Node, duration: float)
@warning_ignore("unused_signal")
signal camp_respawned(camp: Node)
@warning_ignore("unused_signal")
signal creep_last_hit(creep: Node, killer: Node, gold: int)
@warning_ignore("unused_signal")
signal creep_denied(creep: Node, denier: Node)
@warning_ignore("unused_signal")
signal creep_gold_awarded(hero: Node, amount: int, creep_type: int)
@warning_ignore("unused_signal")
signal creep_xp_awarded(hero: Node, amount: int, creep_type: int)
@warning_ignore("unused_signal")
signal creep_killed(creep: Node, killer: Node)
@warning_ignore("unused_signal")
signal gold_awarded(hero: Node, amount: int, reason: String)
@warning_ignore("unused_signal")
signal xp_awarded(hero: Node, amount: int)
@warning_ignore("unused_signal")
signal objective_xp_awarded(hero: Node, amount: int, objective_name: String)
@warning_ignore("unused_signal")
signal hero_kill_xp_awarded(hero: Node, amount: int, victim: Node)
@warning_ignore("unused_signal")
signal hero_kill_gold_awarded(hero: Node, amount: int, victim: Node)
@warning_ignore("unused_signal")
signal assist_gold_awarded(hero: Node, amount: int, victim: Node)
@warning_ignore("unused_signal")
signal passive_gold_ticked(hero: Node, amount: int)
@warning_ignore("unused_signal")
signal hero_gained_xp(hero: Node, current_xp: int, target_xp: int)
@warning_ignore("unused_signal")
signal hero_leveled_up(hero: Node, new_level: int)
@warning_ignore("unused_signal")
signal item_purchased(hero: Node, item: RefCounted)
@warning_ignore("unused_signal")
signal item_sold(hero: Node, item: RefCounted, gold_refund: int)
@warning_ignore("unused_signal")
signal world_item_selected(item_pickup: Node)
@warning_ignore("unused_signal")
signal status_effect_applied(target: Node, effect: RefCounted)
@warning_ignore("unused_signal")
signal status_effect_removed(target: Node, effect: RefCounted)
@warning_ignore("unused_signal")
signal ability_cast(caster: Node, ability: RefCounted, target_point: Vector3, target_node: Variant)
@warning_ignore("unused_signal")
signal ability_cast_started(caster: Node, ability: RefCounted, cast_time: float)
@warning_ignore("unused_signal")
signal ability_cast_interrupted(caster: Node, ability: RefCounted, reason: String)
@warning_ignore("unused_signal")
signal game_state_changed(previous_state: int, new_state: int)
@warning_ignore("unused_signal")
signal match_time_updated(seconds_elapsed: float)
@warning_ignore("unused_signal")
signal day_night_changed(is_day: bool)
@warning_ignore("unused_signal")
signal combat_log_generated(message: String)
@warning_ignore("unused_signal")
signal tower_attack_started(tower: Node, target: Node)
@warning_ignore("unused_signal")
signal tower_destroyed(tower: Node, killer: Node, team_gold: int)
@warning_ignore("unused_signal")
signal tower_retaliated_aggro(tower: Node, enemy_hero: Node, protected_ally: Node)
