@warning_ignore("unused_signal")
class_name GameEventsAutoload
extends Node

## Global decoupled event bus for Eclipse Front

@warning_ignore("unused_signal")
signal target_selected(entity: Node)
@warning_ignore("unused_signal")
signal target_cleared()
@warning_ignore("unused_signal")
signal attack_started(attacker: Node, target: Node)
@warning_ignore("unused_signal")
signal attack_hit(attacker: Node, target: Node, damage_result: RefCounted)
@warning_ignore("unused_signal")
signal attack_landed(attacker: Node, target: Node, damage_result: RefCounted)
@warning_ignore("unused_signal")
signal damage_dealt(damage_result: RefCounted, attacker: Node, target: Node)
@warning_ignore("unused_signal")
signal entity_killed(victim: Node, killer: Node)
@warning_ignore("unused_signal")
signal entity_died(entity: Node, killer: Node)
@warning_ignore("unused_signal")
signal creep_last_hit(creep: Node, killer: Node, gold: int)
@warning_ignore("unused_signal")
signal creep_killed(creep: Node, killer: Node)
@warning_ignore("unused_signal")
signal gold_awarded(hero: Node, amount: int, reason: String)
@warning_ignore("unused_signal")
signal xp_awarded(hero: Node, amount: int)
@warning_ignore("unused_signal")
signal hero_leveled_up(hero: Node, new_level: int)
@warning_ignore("unused_signal")
signal item_purchased(hero: Node, item: RefCounted)
@warning_ignore("unused_signal")
signal item_sold(hero: Node, item: RefCounted, gold_refund: int)
@warning_ignore("unused_signal")
signal status_effect_applied(target: Node, effect: RefCounted)
@warning_ignore("unused_signal")
signal status_effect_removed(target: Node, effect: RefCounted)
@warning_ignore("unused_signal")
signal ability_cast(caster: Node, ability: RefCounted, target_point: Vector3, target_node: Variant)
@warning_ignore("unused_signal")
signal game_state_changed(previous_state: int, new_state: int)
@warning_ignore("unused_signal")
signal match_time_updated(seconds_elapsed: float)
@warning_ignore("unused_signal")
signal day_night_changed(is_day: bool)
@warning_ignore("unused_signal")
signal combat_log_generated(message: String)
@warning_ignore("unused_signal")
signal tower_attack_started(tower: Node, target: Node)
@warning_ignore("unused_signal")
signal tower_destroyed(tower: Node, killer: Node, team_gold: int)
@warning_ignore("unused_signal")
signal tower_retaliated_aggro(tower: Node, enemy_hero: Node, protected_ally: Node)
